### PR TITLE
Added meme functionality

### PR DESCRIPTION
**Pull request by rghv96**
I have added meme functionality as stated in Issue #3 . The memes are scraped from multiple websites. Also, I have added the feature of typing action with which it seems that the bot is really typing the text.

### CODE REVIEW

**Comment by evijit** [comment]
@rghv96 please squash your commits. Especially the 'temp' ones.

**Comment by evijit** [comment]
Your previous commits are still there. You need to do a proper squash.

**Comment by rghv96** [comment]
Is it fine now?

**Comment by evijit** [comment]
Great work! Merging.

**Pull request merged**
